### ISSUE TITLE
Unicode literals

### ISSUE THREAD

**Issue by andrewmwilson** [myint/unify#9]
unify doesn't seem to support changing quotes in unicode literals e.g. `u"example"` is not changed.

Is this the intended behaviour?

**Comment by Zaargh** [comment]
Hey @andrewmwilson !
There was a related issue regarding f-strings (e.g. `f"foo {bar}"`), that was resolved by my PR: https://github.com/myint/unify/pull/4

Adding support for unicode literals should be similar.

**Comment by andrewmwilson** [comment]
Note to myself or anyone else who ends up doing this: the same issues applies to regex strings, ie `r'\bfoo\b`

**Comment by peterjc** [comment]
Both implemented in #11.

**Comment by andrewmwilson** [comment]
Thank you!

**Comment by andrewmwilson** [comment]
Sorry to be a pain, but can we expect a release with this fix?

**Comment by myint** [comment]
Here you go:

https://pypi.org/project/unify/0.5/

**Comment by andrewmwilson** [comment]
Thank you @myint!
